name: Generate release tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  version:
    name: Create new version ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Generate version
        run: npm version ${{ github.event.inputs.version }}

      - name: Push version tag
        run: git push origin main --tags
